apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos-deployment
  labels:
    app: pagamentos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamentos-deployment
  template:
    metadata:
      labels:
        app: pagamentos-deployment
    spec:
      containers:
        - name: app
          image: wellalencar/app-fast-food-pagamentos:latest
          command: ["sh", "-c", "npm run start"]
          ports:
            - containerPort: 6003
          resources:
            requests:
              cpu: 333m
            limits:
              cpu: 999m
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: NODE_ENV
            - name: MONGODB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: MONGODB_CONN_STRING
            - name: MONGODB_DB
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: MONGODB_DB
            - name: SQS_REGION
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: SQS_REGION
            - name: SQS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: SQS_ACCESS_KEY_ID
            - name: SQS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: SQS_SECRET_ACCESS_KEY
            - name: QUEUE_CONFIRMACAO_PAGAMENTO
              valueFrom:
                secretKeyRef:
                  name: secret-pagamentos
                  key: QUEUE_CONFIRMACAO_PAGAMENTO